language: ruby
rvm:
  - 2.3.1
  - 2.2.5
gemfile:
  - ".gemfiles/Gemfile.rails-4.1.x"
  - ".gemfiles/Gemfile.rails-4.2.x"
before_install:
  - gem install bundler --no-doc
deploy:
  provider: rubygems
  api_key:
    secure: GLQ4Kj7WO1ZRIxwfPzlUpYktczqQLfxqPhzMCkrI3N3kVvlLF7cusTGxX3ULmRXqXGmbu7XiSxplw/dCuhVghl51ivekxFF37SLP1zopNV4zw0er7oyGt6R4ZOY6db66jlJQwe3v+/ngrDwmLXUmYPKEtTXePoJgPurozdPbZ5s=
  gem: rails_param
  on:
    tags: true
    repo: nicolasblanco/rails_param
    rvm: 2.3.1
    condition: $BUNDLE_GEMFILE = *rails-4.2.x
