language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - ".gemfiles/Gemfile.rails-4.2.x"
  - ".gemfiles/Gemfile.rails-5.0.x"
  - ".gemfiles/Gemfile.rails-5.1.x"
  - ".gemfiles/Gemfile.rails-5.2.x"
  - ".gemfiles/Gemfile.rails-6.0.x"
matrix:
  exclude:
    - rvm: 2.4
      gemfile: ".gemfiles/Gemfile.rails-6.0.x"
before_install:
  - gem uninstall bundler
  - gem install bundler -v '~> 1.17' --no-doc
deploy:
  provider: rubygems
  api_key:
    secure: GLQ4Kj7WO1ZRIxwfPzlUpYktczqQLfxqPhzMCkrI3N3kVvlLF7cusTGxX3ULmRXqXGmbu7XiSxplw/dCuhVghl51ivekxFF37SLP1zopNV4zw0er7oyGt6R4ZOY6db66jlJQwe3v+/ngrDwmLXUmYPKEtTXePoJgPurozdPbZ5s=
  gem: rails_param
  on:
    tags: true
    repo: nicolasblanco/rails_param
    rvm: 2.6
    condition: $BUNDLE_GEMFILE = *rails-6.0.x
